import { LoginKitTheme, LoginKitThemeColors, LoginKitThemeFonts, ThemeOverrides } from '../types';

const createBaseColors = (): LoginKitThemeColors => ({
  background: '#FFFFFF',
  textShadow: '#f0f0f1',
  text: '#000000',
  gradient: ['#007AFF', '#5856D6'],

  faqsScreeenHeaderTitleColor: '#000000',
  faqsScreeenIconsColor: '#be5300',
  faqsScreeenTooggleIconColor: '#8E8E93',
  faqsScreeenSectionTitle: '#000000',
  faqsScreeenAccordionBgColor: '#2A3436',
  faqsScreeenAccordionShadowColor: '#f0f0f1',
  faqsScreeenAccordionBorderColor: '#E5E5EA',
  faqsScreeenQuestionTextColor: '#000000',
  faqsScreeenAnswerTextColor: '#be5300',
  iconSetSignInAndSignUpScreenIconsColor: '#8E8E93',
  iconSetThemeScreenIconsColor: '#FFD700',
  iconSetAccountScreenResetColor: '#1C54BE',
  iconSetAccountScreenEditColor: '#48515C',
  iconSetAccountScreenImagePickerColor: '#0F877D',
  iconSetAccountScreenDeleteColor: '#A60909',
  themeScreenHeaderTitleColor: '#000000',
  themeScreenSubHeaderTitleColor: '#8E8E93',
  themeScreenCardBgColor: '#2A3436',
  themeScreenCardShadowColor: '#f0f0f1',
  themeScreenToggleContainerColor: '#5856D6',
  themeScreenToggleTextColor: '#FFFFFF',
  loginScreensTextInputBgColor: '#F2F2F7',
  loginScreensTextInputBorderColor: '#2A3436',
  loginScreensTextInputTextColor: '#000000',
  loginScreensTextInputSecondaryTextColor: '#8E8E93',
  loginScreensPrivacyPolicyCheckTrueColor: '#007AFF',
  loginScreensPrivacyPolicyCheckFalseColor: '#8E8E93',
  loginScreensPrivacyPolicyTextColor: '#040498ff',
  loginScreensHaveAnAccountTextColor: '#8E8E93',
  loginScreensHaveAnAccountButtonColor: '#007AFF',
  customAlertCardBgColor: '#2A3436',
  customAlertBorderColor: '#E5E5EA',
  customAlertTitleTextColor: '#FFFFFF',
  customAlertCancelColor: '#ec3c3cff',
  customAlertConfirmColor: '#e7e70aff',
  customAlertOkColor: '#2677c8',
  customAlertSendPrintColor: '#e1cb05ff',
  customAlertButtonTextColor: '#FFFFFF',
  loginScreensTitleColor: '#000000',
  loginScreensSubTitleColor: '#8E8E93',
  loginScreensButtonsColor: '#007AFF',
  loginScreensButtonTextColor: '#FFFFFF',
  loginScreensLogoTextColor: '#000000',
  languageScreenHeaderTitleColor: '#000000',
  languageScreenItemCardBgColor: '#c9daddff',
  languageScreenSelectedLanguageItemBgColor: '#007AFF',
  languageScreenSelectedLanguageItemBorderColor: '#007AFF',
  languageScreenCurrentLanguageItemBgColor: '#FFFFFF',
  languageScreenCurrentLanguageItemBorderColor: '#8E8E93',
  languageScreenAllLanguagesTextColor: '#000000',
  languageScreenEnglishVersionOfAllLanguagesTextColor: '#8E8E93',
  languageScreenSelectedLanguageTextColor: '#FFFFFF',
  languageScreenCurrentLanguageColor: '#000000',
  languageScreenApplyButtonColor: '#007AFF',
  languageScreenApplyButtonTextColor: '#FFFFFF',
  languageScreenProgressTitle: '#000000',
  languageScreenProgressSubTitle: '#8E8E93',
  languageScreenProgressBarContainer: '#007AFF',
  languageScreenProgressBarFill: '#FFFFFF',
  accountScreenPhotoCropperBgColor: '#007AFF',
  accountScreenPhotoCropperTitleColor: '#FFFFFF',
  accountScreenPhotoCropperPreviewContainerBorderColor: '#007AFF',
  accountScreenPhotoCropperButtonBorderColor: '#007AFF',
  accountScreenPhotoCropperOkButtonColor: '#007AFF',
  accountScreenPhotoCropperCancelButtonColor: '#007AFF',
  accountScreenPhotoCropperButtonTextColor: '#FFFFFF',
  accountScreenEditNameModalBgColor: '#007AFF',
  accountScreenEditNameModalBorderColor: '#007AFF',
  accountScreenEditNameModalTitleColor: '#FFFFFF',
  accountScreenEditNameModalTextInputBgColor: '#F2F2F7',
  accountScreenEditNameModalTextInputColor: '#000000',
  accountScreenEditNameModalOkButtonColor: '#007AFF',
  accountScreenEditNameModalCancelButtonColor: '#007AFF',
  accountScreenEditNameModalButtonTextColor: '#FFFFFF',
  accountScreenHeaderTitleColor: '#000000',
  accountScreenHeaderEditPhotoTitleColor: '#000000',
  accountScreenEditPhotoCardBgColor: '#FFFFFF',
  accountScreenAvatarPhotoCardBgColor: '#FFFFFF',
  accountScreenAvatarPhotoCardTextColor: '#000000',
  accountScreenEditPhotoActionButtonsBgColor: '#2d3e50ff',
  accountScreenEditPhotoActionButtonsBorderColor: '#84b1e1ff',
  accountScreenInfoSectionBgColor: '#2A3436',
  accountScreenInfoSectionBorderColor: '#E5E5EA',
  accountScreenInfoSectionLabelTextColor: '#18181dff',
  accountScreenInfoSectionValueTextColor: '#8E8E93',
  accountScreenLogoutButtonColor: '#be2121ff',
});

const createBaseFonts = (): LoginKitThemeFonts => ({
  primaryBlack: 'System',
  primaryExtraBold: 'System',
  primaryBold: 'System',
  primarySemiBold: 'System',
  primaryMedium: 'System',
  primaryRegular: 'System',
  primaryLight: 'System',
  primaryExtraLight: 'System',
  primaryThin: 'System',
})

export const createDefaultTheme = (overrides: ThemeOverrides = {}): LoginKitTheme => ({
  colors: {
    ...createBaseColors(),
    ...overrides.colors,
  },
  fonts: {
    ...createBaseFonts(),
    ...overrides.fonts,
  },
  borderRadius: overrides.borderRadius ?? 12,
});

export const createLightTheme = (overrides: ThemeOverrides = {}): LoginKitTheme => ({
  ...createDefaultTheme(overrides),
  colors: {
    ...createBaseColors(),
    background: '#FFFFFF',
    text: '#000000',
    gradient: ['#007AFF', '#5856D6'],
    ...overrides.colors,
  },
  fonts: {
    ...createBaseFonts(),
    ...overrides.fonts,
  },
  borderRadius: overrides.borderRadius ?? 12,
});

export const createDarkTheme = (overrides: ThemeOverrides = {}): LoginKitTheme => ({
  ...createDefaultTheme(overrides),
  colors: {
    ...createBaseColors(),
    background: '#000000',
    text: '#FFFFFF',
    gradient: ['#5E5CE6', '#0A84FF'],
    ...overrides.colors,
  },
  fonts: {
    ...createBaseFonts(),
    ...overrides.fonts,
  },
  borderRadius: overrides.borderRadius ?? 12,

}); 